const qs=s=>document.querySelector(s);const qsa=s=>[...document.querySelectorAll(s)];
const fmt=v=>v===null||v===undefined||v===''?'–':v;
const DATA=(window.PR_DATA||[]).sort((a,b)=>parseFloat(a.id.replace('PR ',''))-parseFloat(b.id.replace('PR ','')));
const favs=new Set(JSON.parse(localStorage.getItem('prFavs')||'[]'));
const state={tab:'overview',selected:null,search:'',layers:{tracks:true,drive:false,markers:true,satellite:true}};
const map=L.map('map',{zoomControl:false,attributionControl:true,preferCanvas:true,scrollWheelZoom:true,tap:true}).setView([32.755,-16.93],10);
const sat=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'});
const topo=L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenTopoMap'});
const dark=L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:19,attribution:'© OpenStreetMap'});
(state.layers.satellite?sat:dark).addTo(map);
const markerLayer=L.layerGroup().addTo(map), trackLayer=L.layerGroup().addTo(map), driveLayer=L.layerGroup().addTo(map);
function levelClass(l){l=(l||'').toLowerCase(); if(l.includes('leicht'))return'easy'; if(l.includes('schwer'))return'hard'; if(l.includes('mittel'))return'mid'; return'unk'}
function pinHtml(r){return `<div class="pin ${levelClass(r.level)} ${favs.has(r.id)?'fav':''}"><span>${r.id.replace('PR ','PR')}</span></div>`}
function boundsOf(r){let pts=[]; if(r.track?.length)pts=pts.concat(r.track); if(r.driveRoute?.length)pts=pts.concat(r.driveRoute); pts.push([r.lat,r.lon]); return L.latLngBounds(pts)}
function renderLayers(){markerLayer.clearLayers();trackLayer.clearLayers();driveLayer.clearLayers(); DATA.forEach(r=>{ if(state.layers.tracks&&r.track?.length)L.polyline(r.track,{color:'#84ddbf',weight:4,opacity:.94,lineCap:'round'}).addTo(trackLayer); if(state.layers.drive&&r.driveRoute?.length)L.polyline(r.driveRoute,{color:'#ff9f0a',weight:3,opacity:.72,lineCap:'round',dashArray:'7 8'}).addTo(driveLayer); if(state.layers.markers){let ico=L.divIcon({html:pinHtml(r),className:'pr-pin',iconSize:[36,46],iconAnchor:[18,46]}); L.marker([r.lat,r.lon],{icon:ico}).on('click',()=>selectRoute(r.id,true)).addTo(markerLayer);} });}
function fitMadeira(){map.fitBounds([[32.60,-17.28],[32.90,-16.58]],{padding:[20,20]})}
function toast(t){const el=qs('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1500)}
function setBase(){map.eachLayer(l=>{if(l===sat||l===topo||l===dark)map.removeLayer(l)});(state.layers.satellite?sat:dark).addTo(map);}
function saveFavs(){localStorage.setItem('prFavs',JSON.stringify([...favs]));renderLayers();render();}
function selectRoute(id,zoom=false){state.selected=DATA.find(r=>r.id===id); state.tab='detail'; qsa('.nav button').forEach(b=>b.classList.toggle('active',false)); render(); if(zoom&&state.selected)map.fitBounds(boundsOf(state.selected),{paddingTopLeft:[30,120],paddingBottomRight:[30,310],maxZoom:14});}
function routeCard(r){return `<div class="card" onclick="selectRoute('${r.id.replace(/'/g,"\\'")}',true)"><div><div class="detailTitle"><span class="badge ${levelClass(r.level)}">${r.id.replace('PR ','PR ')}</span><div><h3>${r.name}</h3><p>${fmt(r.region)} · ${fmt(r.distanceKm)} km · ${fmt(r.driveMin)} min Anfahrt</p></div></div><div class="meta"><span class="pill">${fmt(r.level)}</span><span class="pill">⛰ ${fmt(r.elevation)} m</span><span class="pill">GPX ${r.hasGpx?'✓':'–'}</span><span class="pill">KML ${r.hasKml?'✓':'–'}</span></div></div><div style="font-size:30px;color:rgba(255,255,255,.4)">›</div></div>`}
function filtered(){let s=state.search.trim().toLowerCase(); let arr=DATA; if(state.tab==='favorites')arr=arr.filter(r=>favs.has(r.id)); if(s)arr=arr.filter(r=>(r.id+' '+r.name+' '+r.region+' '+r.level).toLowerCase().includes(s)); return arr;}
function overview(){return `<div class="stats"><div class="stat"><b>${DATA.length}</b><small>PR-Wege</small></div><div class="stat"><b>${window.PR_SUMMARY?.gpx||0}</b><small>GPX-Tracks</small></div><div class="stat"><b>${window.PR_SUMMARY?.kml||0}</b><small>Anfahrten</small></div></div><div class="searchrow"><input class="search" placeholder="PR suchen…" value="${state.search}" oninput="state.search=this.value;render()"><button class="chipbtn" onclick="fitMadeira()">Karte</button></div><div class="list">${filtered().slice(0,12).map(routeCard).join('')}</div>`}
function routes(){let arr=filtered();return `<div class="searchrow"><input class="search" placeholder="PR, Region, Level…" value="${state.search}" oninput="state.search=this.value;render()"><button class="chipbtn" onclick="state.search='';render()">Reset</button></div><div class="list">${arr.map(routeCard).join('')||'<div class="empty">Keine Treffer.</div>'}</div>`}
function favView(){let arr=filtered();return `<div class="stats"><div class="stat"><b>${arr.length}</b><small>Favoriten</small></div><div class="stat"><b>${arr.reduce((a,r)=>a+(+r.distanceKm||0),0).toFixed(1)}</b><small>km Wege</small></div><div class="stat"><b>${arr.reduce((a,r)=>a+(+r.driveMin||0),0)}</b><small>min Anfahrt</small></div></div><div class="list">${arr.map(routeCard).join('')||'<div class="empty">Noch keine Favoriten markiert.</div>'}</div>`}
function layers(){let Ls=state.layers;return `<div class="layerbox"><button class="toggle ${Ls.satellite?'on':''}" onclick="state.layers.satellite=!state.layers.satellite;setBase();render()"><span>Satellitenkarte</span><b>${Ls.satellite?'Ein':'Aus'}</b></button><button class="toggle ${Ls.markers?'on':''}" onclick="state.layers.markers=!state.layers.markers;renderLayers();render()"><span>PR-Pins</span><b>${Ls.markers?'Ein':'Aus'}</b></button><button class="toggle ${Ls.tracks?'on':''}" onclick="state.layers.tracks=!state.layers.tracks;renderLayers();render()"><span>GPX-Wanderwege</span><b>${Ls.tracks?'Ein':'Aus'}</b></button><button class="toggle ${Ls.drive?'on':''}" onclick="state.layers.drive=!state.layers.drive;renderLayers();render()"><span>KML-Anfahrten</span><b>${Ls.drive?'Ein':'Aus'}</b></button><button class="primary" onclick="map.fitBounds(L.featureGroup([...trackLayer.getLayers(),...markerLayer.getLayers()]).getBounds(),{padding:[35,35]})">Alle sichtbaren Daten einpassen</button></div>`}
function detail(r){let fav=favs.has(r.id);return `<div class="detailTitle"><span class="badge ${levelClass(r.level)}">${r.id}</span><div><h2>${r.name}</h2><p>${fmt(r.region)} · ${fmt(r.level)}</p></div></div><div class="meta"><span class="pill">${fmt(r.distanceKm)} km</span><span class="pill">${fmt(r.duration)}</span><span class="pill">↑ ${fmt(r.high)} m</span><span class="pill">↓ ${fmt(r.low)} m</span><span class="pill">↕ ${fmt(r.elevation)} m</span><span class="pill">🚗 ${fmt(r.driveKm)} km / ${fmt(r.driveMin)} min</span></div><div class="actions"><a class="action" href="${r.startUrl||'#'}" target="_blank"><span>⌖</span>Start</a><a class="action" href="${r.driveUrl||'#'}" target="_blank"><span>🚗</span>Anfahrt</a><button class="action" onclick="${fav?'favs.delete':'favs.add'}('${r.id}');saveFavs()"><span>${fav?'★':'♡'}</span>${fav?'Gemerkt':'Merken'}</button><a class="action" href="${r.officialUrl||'#'}" target="_blank"><span>↗</span>Offiziell</a></div><div class="card"><div><h3>Datenstatus</h3><p>Startkoordinaten aus Master-Excel. GPX: ${r.hasGpx?'vorhanden':'fehlt'} · KML-Anfahrt: ${r.hasKml?'vorhanden':'fehlt'}.</p><p style="margin-top:8px">Parken/Gebühr: ${fmt(r.parking)} / ${fmt(r.fee)}</p>${r.hint?`<p style="margin-top:8px">Hinweis: ${r.hint}</p>`:''}</div></div><button class="primary" onclick="map.fitBounds(boundsOf(state.selected),{paddingTopLeft:[30,120],paddingBottomRight:[30,310],maxZoom:14})">Route auf Karte anzeigen</button>`}
function render(){let html=''; if(state.tab==='overview')html=overview(); else if(state.tab==='routes')html=routes(); else if(state.tab==='favorites')html=favView(); else if(state.tab==='layers')html=layers(); else if(state.tab==='detail')html=detail(state.selected); qs('#content').innerHTML=html;}
qsa('.nav button').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.selected=null;qsa('.nav button').forEach(x=>x.classList.toggle('active',x===b));render();});
qs('#locateBtn').onclick=()=>map.locate({setView:true,maxZoom:13}).on('locationfound',()=>toast('Position ermittelt')).on('locationerror',()=>toast('Position nicht verfügbar'));
renderLayers();render();setTimeout(fitMadeira,250);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
window.selectRoute=selectRoute;window.state=state;window.render=render;window.favs=favs;window.saveFavs=saveFavs;window.boundsOf=boundsOf;window.fitMadeira=fitMadeira;window.renderLayers=renderLayers;window.setBase=setBase;
