const qs=s=>document.querySelector(s);const qsa=s=>[...document.querySelectorAll(s)];
const fmt=v=>v===null||v===undefined||v===''?'–':v;
const DATA=(window.PR_DATA||[]).sort((a,b)=>parseFloat(a.id.replace('PR ',''))-parseFloat(b.id.replace('PR ','')));
const favs=new Set(JSON.parse(localStorage.getItem('prFavs')||'[]'));
let savedStatus=JSON.parse(localStorage.getItem('prStatus')||'{}');
const state={tab:'map',selected:null,query:'',panel:false,menu:null,fullscreen:false,filters:{region:'all',status:'all'},base:'light',layers:{tracks:true,drive:false,heat:false,markers:true,regions:false},lastScroll:0};
const STATUS={open:{key:'open',label:'offen',cls:'green'},limited:{key:'limited',label:'eingeschränkt',cls:'yellow'},closed:{key:'closed',label:'geschlossen',cls:'red'},unknown:{key:'unknown',label:'ungeprüft',cls:''}};
const REGION_GROUPS={center:'Zentrales Hochgebirge',west:'Rabaçal / Paul da Serra',north:'Ribeiro Frio / Santana',east:'Ostkap / Machico',coastwest:'Westliche Steilküsten',porto:'Porto Santo',other:'Nicht zugeordnet'};
function groupFor(r){const id=(r.id||'').trim();const n=(r.name||'').toLowerCase();if(n.includes('pico branco')||n.includes('pico do castelo'))return 'porto';if(['PR 1','PR 1.1','PR 1.2','PR 1.3','PR 2','PR 3','PR 3.1','PR 4','PR 12','PR 17','PR 21','PR 22'].includes(id))return 'center';if(['PR 6','PR 6.1','PR 6.2','PR 6.3','PR 6.4','PR 6.5','PR 6.6','PR 6.8','PR 13','PR 13.1','PR 14','PR 27','PR 28'].includes(id))return 'west';if(['PR 9','PR 9.1','PR 10','PR 11','PR 16','PR 18'].includes(id))return 'north';if(['PR 5','PR 8'].includes(id))return 'east';if(['PR 7','PR 15','PR 19','PR 20'].includes(id))return 'coastwest';return 'other'}
function regionLabel(r){return REGION_GROUPS[groupFor(r)]||REGION_GROUPS.other}

const map=L.map('map',{zoomControl:false,attributionControl:false,preferCanvas:true,tap:true,boxZoom:false}).setView([32.755,-16.93],10);
const baseLayers={
  dark:L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:19}),
  light:L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}),
  topo:L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17}),
  sat:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19})
};
let activeBase=baseLayers[state.base].addTo(map);
const markerLayer=L.layerGroup().addTo(map), trackLayer=L.layerGroup().addTo(map), driveLayer=L.layerGroup().addTo(map), heatLayer=L.layerGroup().addTo(map), regionLayer=L.layerGroup().addTo(map);
let concelhosLoaded=false;
function setZoomClass(){const z=map.getZoom();const app=qs('#app');app.classList.toggle('zoom-far',z<=10);app.classList.toggle('zoom-mid',z>10&&z<=12);app.classList.toggle('zoom-near',z>12);}
map.on('zoomend',setZoomClass);setZoomClass();
function levelClass(l){l=(l||'').toLowerCase(); if(l.includes('leicht'))return'easy'; if(l.includes('schwer'))return'hard'; if(l.includes('mittel'))return'mid'; return'unk'}
function getStatus(id){return savedStatus[id]||'unknown'}
function setStatus(id,status){savedStatus[id]=status;localStorage.setItem('prStatus',JSON.stringify(savedStatus));renderLayers();renderDetail();renderPanel();}
function traffic(status,vertical=false){const s=STATUS[status]||STATUS.unknown;return `<span class="traffic ${vertical?'vertical ':''}${s.cls}"><i class="lamp r"></i><i class="lamp y"></i><i class="lamp g"></i></span>`}
function passFilters(r){if(state.filters.region!=='all' && groupFor(r)!==state.filters.region)return false; if(state.filters.status!=='all' && getStatus(r.id)!==state.filters.status)return false; const q=state.query.trim().toLowerCase(); if(q && !(r.id+' '+r.name+' '+(r.region||'')+' '+regionLabel(r)+' '+(r.level||'')).toLowerCase().includes(q))return false; return true;}
function filtered(){return DATA.filter(passFilters)}
function pinHtml(r){const status=getStatus(r.id);return `<div class="pin ${levelClass(r.level)} ${favs.has(r.id)?'fav':''} ${status}"><span>${r.id.replace('PR ','PR')}</span><i class="statusDot"></i></div>`}
function boundsOf(r){let pts=[]; if(r.track?.length)pts=pts.concat(r.track); if(r.driveRoute?.length)pts=pts.concat(r.driveRoute); if(r.lat&&r.lon)pts.push([r.lat,r.lon]); return L.latLngBounds(pts)}
function allBounds(){const pts=[];filtered().forEach(r=>{if(r.track?.length)pts.push(...r.track); else pts.push([r.lat,r.lon])});return pts.length?L.latLngBounds(pts):L.latLngBounds([[32.60,-17.28],[32.90,-16.58]])}
function renderLayers(){markerLayer.clearLayers();trackLayer.clearLayers();driveLayer.clearLayers();heatLayer.clearLayers(); filtered().forEach(r=>{ if(state.layers.tracks&&r.track?.length)L.polyline(r.track,{color:state.base==='light'||state.base==='topo'?'#0c8f74':'#8ee8c9',weight:2.25,opacity:.72,lineCap:'round',lineJoin:'round',smoothFactor:1.25}).addTo(trackLayer); if(state.layers.drive&&r.driveRoute?.length)L.polyline(r.driveRoute,{color:'#ff6b4a',weight:2.35,opacity:.58,lineCap:'round',lineJoin:'round',smoothFactor:1.4}).addTo(driveLayer); if(state.layers.heat&&r.driveRoute?.length){L.polyline(r.driveRoute,{color:'#ffb000',weight:9,opacity:.18,lineCap:'round',lineJoin:'round',smoothFactor:2}).addTo(heatLayer);L.polyline(r.driveRoute,{color:'#ff3b1f',weight:4,opacity:.22,lineCap:'round',lineJoin:'round',smoothFactor:2}).addTo(heatLayer);} if(state.layers.markers){let ico=L.divIcon({html:pinHtml(r),className:'pr-pin',iconSize:[18,22],iconAnchor:[9,22]}); L.marker([r.lat,r.lon],{icon:ico,riseOnHover:true,keyboard:false}).on('click',()=>openDetail(r.id,true)).addTo(markerLayer);} });setZoomClass();}
function setBase(mode=state.base){state.base=mode;if(activeBase)map.removeLayer(activeBase);activeBase=baseLayers[mode].addTo(map);qs('#app').dataset.base=mode;renderLayers();renderPanel();}
function setMapMode(mode){setBase(mode);}
function toggleHeat(){state.layers.heat=!state.layers.heat;if(state.layers.heat)setBase('light');else renderLayers();renderPanel();}
function toggleRegions(){state.layers.regions=!state.layers.regions;if(state.layers.regions){setBase('light');loadConcelhos();}else{regionLayer.clearLayers();}renderPanel();}
function concelhoStyle(feature){return{color:'rgba(14,24,24,.68)',weight:1.1,fillColor:'#0f8f7a',fillOpacity:.075,dashArray:'3 4'}}
function loadConcelhos(){regionLayer.clearLayers();if(concelhosLoaded&&window.MADEIRA_CONCELHOS){drawConcelhos(window.MADEIRA_CONCELHOS);return;}fetch('https://www.geoboundaries.org/api/current/gbOpen/PRT/ADM2/').then(r=>r.json()).then(meta=>fetch(meta.gjDownloadURL)).then(r=>r.json()).then(g=>{const box=[-17.35,32.58,-16.55,32.92];const feats=(g.features||[]).filter(f=>{const b=bbox(f.geometry);return b&&b[0]<box[2]&&b[2]>box[0]&&b[1]<box[3]&&b[3]>box[1]});window.MADEIRA_CONCELHOS={type:'FeatureCollection',features:feats};concelhosLoaded=true;drawConcelhos(window.MADEIRA_CONCELHOS);}).catch(()=>toast('Regionengrenzen online nicht erreichbar'));}
function bbox(g){let xs=[],ys=[];function walk(c){if(typeof c[0]==='number'){xs.push(c[0]);ys.push(c[1]);}else c.forEach(walk)}try{walk(g.coordinates);return[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)]}catch(e){return null}}
function drawConcelhos(geo){regionLayer.clearLayers();L.geoJSON(geo,{style:concelhoStyle,onEachFeature:(f,l)=>{const name=f.properties.shapeName||f.properties.shapeName_de||f.properties.name||f.properties.NAME_2||'Concelho';l.bindTooltip(name,{sticky:true,className:'regionTooltip'});l.on('click',()=>{state.menu=null;qs('#filterMenu').classList.add('hidden');l.setStyle({fillOpacity:.20,weight:2,color:'rgba(12,120,105,.95)'});const bb=l.getBounds();map.flyToBounds(bb,{padding:[40,40],duration:.75});toast(name);});}}).addTo(regionLayer);}
function fitMadeira(){map.flyToBounds([[32.60,-17.28],[32.90,-16.58]],{padding:[16,16],duration:.9,easeLinearity:.18})}
function fitVisible(){map.flyToBounds(allBounds(),{paddingTopLeft:[28,120],paddingBottomRight:[28,140],maxZoom:14,duration:.9,easeLinearity:.18})}
function toast(t){const el=qs('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1500)}
function showMenu(which){state.menu=state.menu===which?null:which;qs('#viewMenu').classList.toggle('hidden',state.menu!=='view');qs('#filterMenu').classList.toggle('hidden',state.menu!=='filter')}
function setTab(tab){state.tab=tab;state.menu=null;qs('#viewMenu').classList.add('hidden');qs('#filterMenu').classList.add('hidden');qsa('#bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));qs('#navOrb span').textContent=tab==='journal'?'▤':tab==='overview'?'⌂':tab==='trips'?'◉':tab==='options'?'☷':'▱'; if(tab==='map'){hidePanel();return;} openPanel(tab);}
function openPanel(tab){const p=qs('#panel');p.classList.remove('hidden');qs('#app').classList.add('focus-dim');state.panel=true;renderPanel();setTimeout(()=>map.invalidateSize(),180)}
function hidePanel(){qs('#panel').classList.add('hidden');state.panel=false;if(!state.selected)qs('#app').classList.remove('focus-dim');setTimeout(()=>map.invalidateSize(),180)}
function hideDetail(){qs('#detailPanel').classList.add('hidden');state.selected=null;if(!state.panel)qs('#app').classList.remove('focus-dim')}
function openDetail(id,zoom=false){state.selected=DATA.find(r=>r.id===id);hidePanel();qs('#app').classList.add('focus-dim');renderDetail();qs('#detailPanel').classList.remove('hidden');if(zoom&&state.selected){map.flyToBounds(boundsOf(state.selected),{paddingTopLeft:[28,110],paddingBottomRight:[28,250],maxZoom:14,duration:.85,easeLinearity:.18})}}
function collapseNav(){qs('#bottomNav').classList.add('hidden');qs('#navOrb').classList.remove('hidden')}
function expandNav(){qs('#bottomNav').classList.remove('hidden');qs('#navOrb').classList.add('hidden')}
function card(r){const st=getStatus(r.id);return `<div class="card" onclick="openDetail('${r.id}',true)"><div><div class="detailTitle"><span class="badge ${levelClass(r.level)}">${r.id}</span><div><h3>${r.name}</h3><p>${regionLabel(r)} · ${fmt(r.level)} · ${fmt(r.distanceKm)} km</p></div></div><div class="meta"><span class="pill">${traffic(st)} ${STATUS[st].label}</span><span class="pill">🚗 ${fmt(r.driveMin)} min</span><span class="pill">GPX ${r.hasGpx?'✓':'–'}</span></div></div><div style="font-size:30px;color:rgba(255,255,255,.38)">›</div></div>`}
function renderPanel(){const arr=filtered();let html=''; if(state.tab==='overview')html=`<div class="stats"><div class="stat"><b>${DATA.length}</b><small>PR gesamt</small></div><div class="stat"><b>${arr.length}</b><small>sichtbar</small></div><div class="stat"><b>${[...favs].length}</b><small>Favoriten</small></div></div><button class="primary" onclick="setTab('journal')">Journal öffnen</button>`; if(state.tab==='journal')html=`<div class="searchrow"><input class="search" placeholder="PR suchen…" value="${state.query}" oninput="state.query=this.value;renderLayers();renderPanel()"><button class="chipbtn" onclick="showMenu('filter')">Filter</button></div><div class="list">${arr.map(card).join('')||'<div class="empty">Keine PR im aktuellen Filter.</div>'}</div>`; if(state.tab==='trips')html=`<div class="card"><div><h3>Reise Madeira</h3><p>Persönliche Planungsansicht. Favoriten, Status und Filter bleiben lokal auf diesem Gerät gespeichert.</p></div></div><div class="list">${DATA.filter(r=>favs.has(r.id)).map(card).join('')||'<div class="empty">Noch keine Favoriten gesetzt.</div>'}</div>`; if(state.tab==='options')html=optionsHtml(); qs('#panelContent').innerHTML=html;}
function optionsHtml(){const Ls=state.layers;return `<div class="mapModes"><button class="modeChip ${state.base==='light'?'active':''}" onclick="setMapMode('light')">OSM hell</button><button class="modeChip ${state.base==='dark'?'active':''}" onclick="setMapMode('dark')">Dark</button><button class="modeChip ${state.base==='topo'?'active':''}" onclick="setMapMode('topo')">Topo</button><button class="modeChip ${state.base==='sat'?'active':''}" onclick="setMapMode('sat')">Satellit</button></div><div class="list"><button class="card" onclick="state.layers.markers=!state.layers.markers;renderLayers();renderPanel()"><b>PR-Pins</b><span>${Ls.markers?'Ein':'Aus'}</span></button><button class="card" onclick="state.layers.tracks=!state.layers.tracks;renderLayers();renderPanel()"><b>GPX-Wanderwege</b><span>${Ls.tracks?'Ein':'Aus'}</span></button><button class="card" onclick="state.layers.drive=!state.layers.drive;renderLayers();renderPanel()"><b>KML-Anfahrten</b><span>${Ls.drive?'Ein':'Aus'}</span></button><button class="card" onclick="toggleHeat()"><b>Anfahrts-Heatmap</b><span>${Ls.heat?'Ein':'Aus'}</span></button><button class="card" onclick="toggleRegions()"><b>Concelhos Orientierung</b><span>${Ls.regions?'Ein':'Aus'}</span></button></div><button class="primary" onclick="fitVisible();setTab('map')">Sichtbare PR einpassen</button>`}
function renderDetail(){if(!state.selected)return;const r=state.selected, fav=favs.has(r.id), st=getStatus(r.id);qs('#detailContent').innerHTML=`<div class="detailTitle"><span class="badge ${levelClass(r.level)}">${r.id}</span><div><h2>${r.name}</h2><p>${regionLabel(r)} · ${fmt(r.level)}</p></div></div><div class="meta"><span class="pill">${fmt(r.distanceKm)} km</span><span class="pill">${fmt(r.duration)}</span><span class="pill">↑ ${fmt(r.high)} m</span><span class="pill">↓ ${fmt(r.low)} m</span><span class="pill">🚗 ${fmt(r.driveKm)} km / ${fmt(r.driveMin)} min</span></div><div class="statusPanel"><h3>Status manuell setzen</h3><div class="statusButtons"><button class="${st==='open'?'active':''}" onclick="setStatus('${r.id}','open')">${traffic('open')} offen</button><button class="${st==='limited'?'active':''}" onclick="setStatus('${r.id}','limited')">${traffic('limited')} begrenzt</button><button class="${st==='closed'?'active':''}" onclick="setStatus('${r.id}','closed')">${traffic('closed')} zu</button></div></div><div class="actions"><a class="action" href="${r.startUrl||'#'}" target="_blank"><span>⌖</span>Start</a><a class="action" href="${r.driveUrl||'#'}" target="_blank"><span>🚗</span>Anfahrt</a><button class="action" onclick="${fav?'favs.delete':'favs.add'}('${r.id}');saveFavs()"><span>${fav?'★':'♡'}</span>${fav?'Gemerkt':'Merken'}</button><a class="action" href="${r.officialUrl||'#'}" target="_blank"><span>↗</span>Offiziell</a></div><div class="card"><div><h3>Datenstatus</h3><p>Startkoordinaten aus Master-Excel. GPX: ${r.hasGpx?'vorhanden':'fehlt'} · KML-Anfahrt: ${r.hasKml?'vorhanden':'fehlt'}.</p><p style="margin-top:8px">Parken/Gebühr: ${fmt(r.parking)} / ${fmt(r.fee)}</p>${r.hint?`<p style="margin-top:8px">Hinweis: ${r.hint}</p>`:''}</div></div><button class="primary" onclick="map.flyToBounds(boundsOf(state.selected),{paddingTopLeft:[28,100],paddingBottomRight:[28,140],maxZoom:14,duration:.85,easeLinearity:.18});hideDetail();setTab('map')">Route anzeigen</button>`}
function saveFavs(){localStorage.setItem('prFavs',JSON.stringify([...favs]));renderLayers();renderDetail();renderPanel()}
function renderFilterMenus(){const keys=Object.keys(REGION_GROUPS).filter(k=>DATA.some(r=>groupFor(r)===k));qs('#regionFilters').innerHTML=`<button class="filterChip ${state.filters.region==='all'?'active':''}" onclick="state.filters.region='all';applyFilters()">Alle</button>`+keys.map(k=>`<button class="filterChip ${state.filters.region===k?'active':''}" onclick="state.filters.region='${k}';applyFilters()">${REGION_GROUPS[k]}</button>`).join(''); const opts=['open','limited','closed'];qs('#statusFilters').innerHTML=`<div class="statusFilterTitle">Routen-Status:</div>`+opts.map(x=>`<button aria-label="${STATUS[x].label}" class="statusChoice dotOnly ${state.filters.status===x?'active':''}" onclick="state.filters.status=state.filters.status==='${x}'?'all':'${x}';applyFilters()">${traffic(x,true)}</button>`).join('')}
function applyFilters(){renderFilterMenus();renderLayers();renderPanel();if(filtered().length)fitVisible();}
function resetFilters(){state.filters={region:'all',status:'all'};state.query='';applyFilters()}
function setFullscreen(on){state.fullscreen=on;hidePanel();hideDetail();qs('#app').classList.toggle('fullscreen',on);qs('#fullscreenClose').classList.toggle('hidden',!on);state.menu=null;qs('#viewMenu').classList.add('hidden');qs('#filterMenu').classList.add('hidden');if(on)collapseNav();else expandNav();setTimeout(()=>map.invalidateSize(),180)}
function bind(){qs('#viewBtn').onclick=()=>showMenu('view');qs('#filterBtn').onclick=()=>showMenu('filter');qs('#fitAllBtn').onclick=()=>{fitVisible();showMenu('view')};qs('#fullscreenBtn').onclick=()=>setFullscreen(true);qs('#fullscreenClose').onclick=()=>setFullscreen(false);qs('#detailClose').onclick=hideDetail;qs('#resetFilters').onclick=resetFilters;qs('#locateBtn').onclick=()=>map.locate({setView:true,maxZoom:13}).on('locationfound',()=>toast('Position ermittelt')).on('locationerror',()=>toast('Position nicht verfügbar'));qsa('#bottomNav button').forEach(b=>b.onclick=()=>{expandNav();setTab(b.dataset.tab)});qs('#navOrb').onclick=expandNav;qs('#panel').addEventListener('scroll',()=>{const y=qs('#panel').scrollTop;if(y>34)collapseNav(); if(y<8)expandNav(); state.lastScroll=y;},{passive:true});map.on('click',()=>{state.menu=null;qs('#viewMenu').classList.add('hidden');qs('#filterMenu').classList.add('hidden')});}
window.openDetail=openDetail;window.setTab=setTab;window.showMenu=showMenu;window.state=state;window.favs=favs;window.saveFavs=saveFavs;window.setStatus=setStatus;window.applyFilters=applyFilters;window.hideDetail=hideDetail;window.boundsOf=boundsOf;window.setMapMode=setMapMode;window.toggleHeat=toggleHeat;window.toggleRegions=toggleRegions;
renderFilterMenus();bind();renderLayers();setTab('map');setTimeout(fitMadeira,250);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
